import Footer from '@/components/ui/footer';
import Header from '@/components/ui/header';
import clsx from 'clsx';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Find Falcone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head></head>
      <body className={clsx(poppins.className, 'min-h-screen')}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
